WrathStoryTracker_QUESTS_BY_ZONE = {
  ["Borean Tundra"] = {
    {id=11672, name="Enlistment Day"},
    {id=11692, name="Check In With Bixie"},
    {id=11791, name="Notify Arlos"},
    {id=11932, name="Cowards and Fools"},
    {id=11968, name="The Tides Turn"},
    {id=12088, name="Thassarian, the Death Knight"},
    {id=12099, name="Free at Last"},
    {id=12100, name="Containing the Rot"},
  },
  ["Howling Fjord"] = {
    {id=11243, name="If Valgarde Falls..."},
    {id=11253, name="Sniff Out the Enemy"},
    {id=11275, name="Making the Horn"},
    {id=11343, name="The Echo of Ymiron"},
    {id=11428, name="Keeper Witherleaf"},
    {id=11453, name="The Jormungar are Coming!"},
    {id=11504, name="The Dead Rise!"},
  },
  ["Dragonblight"] = {
    {id=12000, name="Rifle the Bodies"},
    {id=12057, name="The Flesh-Bound Tome"},
    {id=12068, name="Voices from the Dust"},
    {id=12069, name="Return of the High Chief"},
    {id=12110, name="End Arcanimus"},
    {id=12119, name="Gaining an Audience"},
    {id=12157, name="The Lost Courier"},
    {id=12201, name="The Overseer's Shadow"},
    {id=12261, name="No Place to Run"},
    {id=12267, name="Neltharion's Flame"},
    {id=12277, name="Leave Nothing to Chance"},
    {id=12372, name="Defending Wyrmrest Temple"},
  },
  ["Grizzly Hills"] = {
    {id=12207, name="Vordrassil's Seeds"},
    {id=12220, name="A Dark Influence"},
    {id=12246, name="A Possible Link"},
    {id=12278, name="Find Kurun!"},
    {id=12307, name="Wolvar Faction"},
    {id=12413, name="Attack on Silverbrook"},
    {id=12444, name="Blackriver Skirmish"},
    {id=12481, name="Adding Injury to Insult"},
  },
  ["Zul'Drak"] = {
    {id=12503, name="Defend the Stand"},
    {id=12552, name="Death to the Necromagi"},
    {id=12610, name="Clipping Their Wings"},
    {id=12641, name="Death Comes From On High"},
    {id=12661, name="Infiltrating Voltarus"},
    {id=12677, name="Hazardous Materials"},
    {id=12713, name="Betrayal"},
    {id=12795, name="Taking a Stand"},
    {id=12859, name="This Just In: Fire Still Hot!"},
  },
  ["Sholazar Basin"] = {
    {id=12524, name="Venture Co. Misadventure"},
    {id=12546, name="Reclamation"},
    {id=12556, name="Back So Soon?"},
    {id=12611, name="Returned Sevenfold"},
    {id=12644, name="Still At It"},
    {id=12688, name="Engineering a Disaster"},
    {id=12797, name="Back Through the Waygate"},
  },
  ["The Storm Peaks"] = {
    {id=12818, name="Clean Up"},
    {id=12843, name="They Took Our Men!"},
    {id=12878, name="The Hidden Relic"},
    {id=12900, name="Making a Harness"},
    {id=12973, name="The Brothers Bronzebeard"},
    {id=12997, name="Into the Frozen Heart of Northrend"},
    {id=13000, name="Emergency Measures"},
    {id=13047, name="The Reckoning"},
  },
  ["Icecrown"] = {
    {id=12891, name="I Have an Idea, But First..."},
    {id=12938, name="The Duke"},
    {id=12982, name="Ebon Blade Prisoners"},
    {id=13007, name="The Unbreakable Will"},
    {id=13068, name="A Tale of Valor"},
    {id=13104, name="Once More Unto The Breach, Hero"},
    {id=13141, name="The Battle For Crusaders' Pinnacle"},
    {id=13367, name="No Rest For The Wicked"},
    {id=13372, name="The Key to the Focusing Iris"},
    {id=13419, name="Preparations for War"},
  },
}

WrathStoryTracker_ZONE_ORDER = {
  "Borean Tundra",
  "Howling Fjord",
  "Dragonblight",
  "Grizzly Hills",
  "Zul'Drak",
  "Sholazar Basin",
  "The Storm Peaks",
  "Icecrown"
}